version: '3'
services:
  api:
    container_name: todo-api
    build: 
      context: .
      dockerfile: ./build/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
  
      #nginx:
    #container_name: nginx
    #build:
      #context: .
      #dockerfile: ./build/nginx/Dockerfile
      #ports:
      #- "80:80"
        #depends_on:
      #- api
