name: CI
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: checkout
        uses: actions/checkout@v1

      - name: test
        run: go test ./... -v
