name: CI
on:
  push:
    branches:
    - "**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: get dependencies
        run: go get -v -t -d ./...

      - name: test
        run: go test ./... -v
